# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0270cc3ff276192c84d3bfcbbca5e4298f22e6a0a9202c382b213ea15c0c466efdcb20d9328db2216448541d1664e1bc96a96d64d15b93777bfbf033e791a03b

test:
  secret_key_base: d76f8eb9122b0ec990625f109ea3dd82a982e001b5dcbc06db1bd2e7972ee6aeb28ec3cc7b63d7bbe64757b1ddd22c4c75a1f9bf3679c88d776a17e8533322de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
